/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  watchman: false,
  roots: ['<rootDir>'],
  modulePathIgnorePatterns: ['<rootDir>/dist'],
  testMatch: ['**/tests/**/*.test.ts'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    '*.ts',
    'config/**/*.ts',
    'middleware/**/*.ts',
    'routes/**/*.ts',
    'services/**/*.ts',
    'utils/**/*.ts',
    '!**/*.d.ts',
    '!dist/**',
    '!tests/**',
    '!models/**',
    '!server.ts',
    '!routes/openapi-mobile-contracts.ts',
    '!routes/test.ts',
    '!middleware/upload.ts',
    '!services/fileStorage.ts',
    '!services/notificationService.ts',
    '!config/config.ts',
    '!config/database.ts',
    '!scripts/**',
  ],
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 80,
      lines: 85,
      statements: 85,
    },
  },
  testTimeout: 30000,
};
